p1: helloStreamServer.py
        python helloStreamServer.py

p2: helloStreamClient.py
        python helloStreamClient.py

p3: helloDgramServer.py
        python helloDgramServer.py

p4: helloDgramClient.py
        python helloDgramClient.py







